spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/metering?characterEncoding=utf-8&useSSL=false&useUnicode=true&serverTimezone=CTT
    username: root
    password: root
  thymeleaf:
    cache: false




server:
  port: 8080




